### ISSUE TITLE
Very excited to see this!

### ISSUE THREAD

**Issue by photex** [stepancheg/grpc-rust#1]
Due to a lack of options we started with c++ at work but it will be great to be able to put some rust implemented services into production at some point.

When you come to a point far enough along to have some TODO items I'd be happy to contribute.

**Comment by rafaelwkerr** [comment]
I'm very excited to contribute to this approach :)

**Comment by stepancheg** [comment]
I'm closing the issue now.

I've updated the TODO section in the readme, feel free to grab anything you want )
