### ISSUE TITLE
TLS support in client

### ISSUE THREAD

**Issue by vrusinov** [stepancheg/grpc-rust#11]
I have a server (implemented in golang) that requires clients to connect with TLS.
So I've tried to implement TLS support in grpc-rust, which, in theory, should be relatively easy: grpc works over standard HTTP2 + tls. For now, I don't need any cert validation, I just want _some_ security over the wire.

However, I got stuck and I think I need some help/explaining.

I was hoping I could just propagate different value of `http_scheme` to solicit and it will do everything for me. So far I've managed to add `http_scheme` param to `GrpcClient::new` and propagate it to `HttpClientConnectionAsync`. But then it looks like you are doing handshake manually in `solicit_async.rs` and it's just static string, and you are doing most of the http-related stuff semi-manually.

Can you give me some advice here? Should I try to replace client_handshake with something provided by solicit? Or, maybe I should look at [tokio_tls](https://tokio-rs.github.io/tokio-tls/tokio_tls/index.html) and pass it instead of `TcpStream`?

**Comment by stepancheg** [comment]
> Should I try to replace client_handshake with something provided by solicit?

No, because solicit only supports synchronous API.

> Or, maybe I should look at tokio_tls and pass it instead of TcpStream?

Yes, I think that would work (although it will require significant amount of changes in grpc-rust).

Or you can wait till I implement it myself (I'm planning to do it, but currently I'm busy implementing better protobuf 3 support in rust-protobuf).

**Comment by stepancheg** [comment]
Added client code: 12e1059c98872c97c62fb062357195534bd70e71, but haven't tested it. It won't work likely.

See also https://github.com/tokio-rs/tokio-tls/issues/6

**Comment by stepancheg** [comment]
Should work now.
