### ISSUE TITLE
Looks like futures dep needs to be updated.

### ISSUE THREAD

**Issue by thedodd** [stepancheg/grpc-rust#112]
Futures version `0.2` is not backwards compatible with version `0.1`. Should probably update the dependency to indicate that this is actually dependent upon `futures 0.1.*`.

**Comment by kali** [comment]
Thanks for the fix, any chance we get a new release soon including it ?

**Comment by stepancheg** [comment]
I'll do it now.

**Comment by stepancheg** [comment]
Published v0.3.0. Thank you for the ping!

**Comment by kali** [comment]
thanks you :)
