### ISSUE TITLE
UnexpectedEof when client connection ends

### ISSUE THREAD

**Issue by mcesar** [stepancheg/grpc-rust#122]
If we enable logging in greeter_server and run greeter_client we will see the following warning on server:

WARN:<unknown>: connection end: IoError(Custom { kind: UnexpectedEof, error: StringError("early eof") })

Is it something we must worry about? How to prevent this warning?

**Comment by mcesar** [comment]
Thanks for the reply. Is there a fix planned in rust-http2?

**Comment by stepancheg** [comment]
I have created [an issue](https://github.com/stepancheg/rust-http2/issues/31).
