### ISSUE TITLE
2.0 protobuf incompatible with GRPC generation 

### ISSUE THREAD

**Issue by przygienda** [stepancheg/grpc-rust#127]
42 |                 req_marshaller: Box::new(::grpc::protobuf::MarshallerProtobuf),
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `protobuf::core::Message` is not implemented for `...service::LoginRequest`

basically looks like the message trait been moved around & code broke ...

**Comment by przygienda** [comment]
problem exists if trying to compile with protobuf="~2.0"

code genreated with 2.0 compiles fine with protobuf="~1.6" 

nightly 2-3 weeks ago ...

**Comment by stepancheg** [comment]
I plan to switch grpc to protobuf `~2.0` soon.

**Comment by stepancheg** [comment]
Done, published grpc `0.5.0`

**Comment by przygienda** [comment]
thanks ;-)
