### ISSUE TITLE
stops working when using in a loop

### ISSUE THREAD

**Issue by timglabisch** [stepancheg/grpc-rust#13]
i tryed rust-rpc, here is the code:

https://github.com/timglabisch/grpc_examples/blob/a56e668958e19b6b84ba069620012eb1af553673/rust_server/src/main.rs

when i run the php client `php example.php` gprc-rust and the php client are working well together.
after a few thousand messages (depends on the package (string) length), grpc-rust stops working. it's totally reproducable. the node grpc implementation works, so it must be an issue with grpc-rust

**Comment by stepancheg** [comment]
Yes, I think the bug is in gRPC. HTTP/2 implementation in grpc-rust is very incomplete, and I think the reason behind hanging is missing window implementation (currently gRPC simply ignores WINDOW frames and does not sent it, which is wrong).

I'm going to fix it soon.

**Comment by stepancheg** [comment]
This particilar issues must be fixed in 39a07b687f6f88d1001139a8603a79b910d71afd.

Although window support is far from complete.
