### ISSUE TITLE
looks like tokio-io 0.1.10 just broke GRPC ...

### ISSUE THREAD

**Issue by przygienda** [stepancheg/grpc-rust#131]
all said, connection timeout immediately, 0.1.9 works ... I'm looking @ other crates but tokio-io has just been updated & all stopped ...

**Comment by stepancheg** [comment]
If you can provide an example reproducing hanging, that will help.

**Comment by przygienda** [comment]
yah, 0.1.12 tokio publish has been yanked. Sigh, 2AM yesterday ...
