### ISSUE TITLE
lack of Clone trait on grpc::Client v.0.6

### ISSUE THREAD

**Issue by przygienda** [stepancheg/grpc-rust#132]
grpc::CLient used to be :Clone on v.0.4 and the removal of that (why? http client inside is Arc!) breaks lots of APIs that on creation consume a grpc client.  This forces now to open an HTTP connection for every client in an API where before it could be generated by with_client so multiple services could be run on same HTTPbis ...  

any rationale? 

I will fork 0.6.0 and add the Clone derive & try to upstream but some sane remedy would be appreciated ...

**Comment by stepancheg** [comment]
I'm not sure what's the proper design, my thoughts are these.

It is simply not necessary and complicates implementation a bit.

If you need to access client from multiple threads, you can put `Client` into `Arc<Client>`, because `Client` is `Sync` anyway.

BTW API/design/implementation feedback is always welcome.

**Comment by stepancheg** [comment]
> The generated code necessitates a straight grpc::Client move into the API

Nope. I've just double-checked in v6.0 branch, generated code is:

```
pub struct GreeterClient {
    grpc_client: ::std::sync::Arc<::grpc::Client>,
    method_SayHello: ::std::sync::Arc<::grpc::rt::MethodDescriptor<super::helloworld::HelloRequest, super::helloworld::HelloReply>>,
}

impl ::grpc::ClientStub for GreeterClient {
    fn with_client(grpc_client: ::std::sync::Arc<::grpc::Client>) -> Self {
        GreeterClient {
            grpc_client: grpc_client,
            method_SayHello: ::std::sync::Arc::new(::grpc::rt::MethodDescriptor {
                name: "/helloworld.Greeter/SayHello".to_string(),
                streaming: ::grpc::rt::GrpcStreaming::Unary,
                req_marshaller: Box::new(::grpc::protobuf::MarshallerProtobuf),
                resp_marshaller: Box::new(::grpc::protobuf::MarshallerProtobuf),
            }),
        }
    }
}

impl Greeter for GreeterClient {
    ...
}
```

**Comment by przygienda** [comment]
ok, look like I possibly did run the build.rs with a different rust grpc than the main package extern ... investigating ...

**Comment by przygienda** [comment]
ok, yepp, let me close the pullup. That was the reason. Nast'ish stuff. Maybe putting into generated code some indication _which_ version of grpc rust generated the backend would be helpful. Would allow compile time checks ...

**Comment by stepancheg** [comment]
> Maybe putting into generated code some indication which version of grpc rust generated the backend would be helpful

https://github.com/stepancheg/grpc-rust/issues/134

Also, I'm thinking about making generated code with a different version of grpc should be a compile-time error, like this:

grpc:
```
const VERSION_0_6_0: () = ();
```

generated_code:
```
const _VERSION: () = grpc::VERSION_0_6_0;
```

This is possible to implement, however, this will require client code regeneration in minor versions even if the generated code is compatible.
