### ISSUE TITLE
Please add a serde_derive feature

### ISSUE THREAD

**Issue by zutils** [stepancheg/grpc-rust#139]
protobuf_codegen_pure allows us to customize our input. Please add serde_derive so that we can derive any auto-generated code from serde.

**Comment by stepancheg** [comment]
> protobuf_codegen_pure allows us to customize our input

Not just `protobuf_codegen_pure` (pure Rust), but also `protoc_rust` (which depend on `protoc`).

Note `protoc_grpc_rust` depends on  `protoc_rust`, not `protobuf_codegen_pure`.

Pure rust grpc codegen is not yet implemented.

> Please add serde_derive so that we can derive any auto-generated code from serde.

Well, I think `protoc_grpc_rust` should have a field of type `protobuf_codegen::Customize` to pass it further to `protoc_rust`.

I can do it later, but the patch is welcome, should be easy.

**Comment by stepancheg** [comment]
Should be fixed now.

FYI I did not plan to release a new version until I rewrite grpc-rust to sink API.
