### ISSUE TITLE
The generated rust file can't be compiled successfully because of failed to resolve: could not find `grpc_protobuf` in `{{root}}`

### ISSUE THREAD

**Issue by cylof22** [stepancheg/grpc-rust#147]
The generated rust file compile unsuccessfully because of failed to resolve: could not find `grpc_protobuf` in `{{root}}`

**Comment by PeopleDispose** [comment]
@cylof22 
I got this problem as well while developing project using one of the tutorials. But after adding a few more dependencies mentioned in README, cargo was managed to compile project successfully.

**Comment by cylof22** [comment]
@PeopleDispose Thanks for your comments. The crate version is not correct in my project.
