### ISSUE TITLE
rust_out option fails

### ISSUE THREAD

**Issue by wbl** [stepancheg/grpc-rust#166]
$protoc --rust-grpc_out=. --rust_out=. warp.proto 
protoc-gen-rust: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--rust_out: protoc-gen-rust: Plugin failed with status code 1.

This happens after installing grpc-compiler as the readme (https://github.com/stepancheg/grpc-rust/tree/master/grpc-compiler) says to do. I'm sure this will be solved by installing another package, but it isn't clear which one.

**Comment by wbl** [comment]
Update: cargo install protobuf-codegen is the magic invocation I required and then it Just Worked.

**Comment by stepancheg** [comment]
So I'm closing now. Please reopen if the issue starts to reproduce again.
