### ISSUE TITLE
Generates code with allow(clippy) instead of allow(clippy::all)

### ISSUE THREAD

**Issue by jknovi** [stepancheg/grpc-rust#178]
This is causing some deprecated warnings.

Just need to change this line:

https://github.com/stepancheg/grpc-rust/blob/master/grpc-compiler/src/codegen.rs#L45

**Comment by ec2** [comment]
Seeing the same issue here. Is there a way to get Clippy to ignore those generated files meanwhile?

**Comment by jknovi** [comment]
I wasn't able to ignore them, right now my "work-around" is to build grpc-rust locally with a patch, that I'm planning to send a PR soon-ish (my contractual obligations force me to do some bureaucratic paperwork before contributing to open source :( ) , but is just one line, if you have the time to spare is a low-hanging fruit.

**Comment by ec2** [comment]
Just opened a PR on that :)

**Comment by stepancheg** [comment]
Published 0.7.1. Please let me know if need to be merged into 0.6 branch.
