### ISSUE TITLE
Q: is it possible to use grpc-rust with C based Protocol Buffers?

### ISSUE THREAD

**Issue by mw66** [stepancheg/grpc-rust#199]
Hi,

Maybe this is a silly question: but is it possible to use grpc-rust with C based Protocol Buffers ? e.g.

https://github.com/nanopb/nanopb (for memory restricted system).

https://github.com/protobuf-c/protobuf-c

I think the output of those library are just C's struct, is it possible to use grpc-rust with these struct to achieve network communication?

Thanks!

**Comment by stepancheg** [comment]
No, it can only be used with rust-protobuf.

Note this project is mostly abandoned.
