### ISSUE TITLE
WINDOW_UPDATE spec is not followed

### ISSUE THREAD

**Issue by stevej** [stepancheg/grpc-rust#25]
(I have a half-finished patch that I'll post for review so we can discuss whether you like the API or think it's placed at the right layer)

As we write bytes to a peer we don't properly account for the required changes to the window size. This results in FLOW_CONTROL_ERROR errors from peers in my interop testing with grpc-go (and also the occasional panic from grpc-go).

**Comment by stepancheg** [comment]
Should be fixed now.
