### ISSUE TITLE
How to register multiple services?

### ISSUE THREAD

**Issue by overvenus** [stepancheg/grpc-rust#28]
Hello @stepancheg,

I'm curious to know how to register multiple services in one gRPC server.
I found that the current compiler generates Servers that only serve one service.

E.g. [LongTestsAsyncServer]

```rust
    // new() creates a gRPC server and a LongTestsServer.
    let _server = LongTestsAsyncServer::new(23432, LongTestsServerImpl{});
```

*LongTestsAsyncServer* listens on 23432 and only responds to rpcs that are
defined in [long_tests_pb.proto]. It seems there is no api that allows adding
other services.

I think the problem is `LongTestsAsyncServer` is a service server, and meanwhile
it's a **gRPC** server.

Maybe it should be generated to something like Go or Java, so that we can add
more services later.

 + [Go]

```go
    s := grpc.NewServer()
    pb.RegisterLongTestsServer(s, &server{})
    // pb.RegisterOtherServer(s, &otherserver{})
    // and more ...
```

 + [Java]

```java
    server = ServerBuilder.forPort(port)
        .addService(new GreeterImpl())
        // .addService(new OtherImpl())
        // and more ...
        .build()
        .start();
```

[LongTestsAsyncServer]: https://github.com/stepancheg/grpc-rust/blob/16ebda674fe030383b48ab2f4c7d571f8b1a2d5a/long-tests/with-rust/src/bin/long_tests_server.rs#L65
[long_tests_pb.proto]: https://github.com/stepancheg/grpc-rust/blob/16ebda674fe030383b48ab2f4c7d571f8b1a2d5a/long-tests/long_tests_pb.proto
[Go]: https://github.com/grpc/grpc-go/blob/c8105071640ef29fce843ed96983e864bb18eb0e/examples/helloworld/greeter_server/main.go#L63
[Java]: https://github.com/grpc/grpc-java/blob/322eb8c5c5a5b655730a084eb4c4be6516938b7c/examples/src/main/java/io/grpc/examples/helloworld/HelloWorldServer.java#L52

Thanks and happy new year :tada:!

**Comment by stepancheg** [comment]
It should be possible now like this:

```
let greeter = GreeterServiceAsync::new_service_def(greeter_handler);
let other = OtherServiceAsync::new_service_def(other_handler);
let service_def = ServiceDefinition::join(vec![greeter, other]);
GrpcServer::new(addr, service_def);
```
