### ISSUE TITLE
import "google/protobuf/empty.proto";

### ISSUE THREAD

**Issue by kkimdev** [stepancheg/grpc-rust#31]
It seems like importing "google/protobuf/...*proto" is not supported out-of-the-box? I'm getting the following error when I tried to use `google.protobuf.Empty`.

```
24 |     fn GetId(&self, p: super::empty::Empty) -> ::grpc::result::GrpcResult<super::m19g::PlayerId>;
   |                        ^^^^^^^^^^^^^^^^^^^ Maybe a missing `extern crate empty;`?
```

**Comment by stepancheg** [comment]
I'm not sure yet what is correct behavior here.

Anyway, could you please reopen the issue in [rust-protobuf](https://github.com/stepancheg/rust-protobuf/)? It belongs there.

**Comment by kkimdev** [comment]
Filed https://github.com/stepancheg/rust-protobuf/issues/197
