### ISSUE TITLE
Check in Cargo.lock

### ISSUE THREAD

**Issue by kerinin** [stepancheg/grpc-rust#5]
I'm having trouble building - would you mind checking in your Cargo.lock file so I can use the same versions of libraries?  Specifically I'm currently getting the following error when building:

```
src/futures_misc/task_data.rs:5:5: 5:28 error: unresolved import `futures::task::TaskData`. There is no `TaskData` in `futures::task` [E0432]
src/futures_misc/task_data.rs:5 use futures::task::TaskData;
```

**Comment by stepancheg** [comment]
That's because futures-rs and tokio has been [changed yesterday](https://github.com/alexcrichton/futures-rs/commit/82460a6121d52bd4f3ef51c4b19a38b2e947752e). It is [broken everywhere](https://travis-ci.org/stepancheg/grpc-rust) (and I've lost `Cargo.lock` that worked), I'm going to fix it soon.

**Comment by stepancheg** [comment]
It mostly works now, except this issue https://github.com/tokio-rs/tokio-core/issues/12 needs to be fixed.
