### ISSUE TITLE
use a thread name for the event loop 

### ISSUE THREAD

**Issue by siddontang** [stepancheg/grpc-rust#56]
Hi @stepancheg 

Now you use `thread::spawn` to start the event loop thread, it is not convenient to know the thread CPU takes with `top -H`. It is better to pass a customized thread name in config, or we can use `grpc-server-loop` or `grpc-client-loop` by default.

If you think it is fine, we can send you a PR.

**Comment by stepancheg** [comment]
Thank you for the suggestion!
