### ISSUE TITLE
Upload to crates

### ISSUE THREAD

**Issue by vrusinov** [stepancheg/grpc-rust#6]
I see you have this in TODO, but filing an issue so that github can notify me when this happens.

Also, there's some namesquatting already happens: https://crates.io/crates/grpc-rust :)

**Comment by stepancheg** [comment]
No problem.

Actually, I also did namesquatting: https://crates.io/crates/grpc :)

Currently
* grpc-rust has too many bugs
* some important features are not implemented
* futures-rs and tokio-core were uploaded to crates just yesterday

Please let me know if you need grpc-rust uploaded to crates even if is not ready yet. Note: you can always use grpc-rust right from git:

```
[dependencies]
grpc = { git = "http://github.com/stepancheg/grpc-rust" }
```

**Comment by vrusinov** [comment]
It's your decision whether to upload it now or not. I just want to be notified via this issue when I could replace git = in my [dependencies] :)

Personally I'd say it's good enough for upload, since it seems to be somewhat functional and it may be a good way to increase visibility and draw more contributors here.

**Comment by stepancheg** [comment]
Uploaded to crates: [grpc](https://crates.io/crates/grpc) and [grpc-compiler](https://crates.io/crates/grpc-compiler).

It does not mean grpc-rust is ready for production.
