### ISSUE TITLE
propose: export GrpcServer local_addr functions

### ISSUE THREAD

**Issue by siddontang** [stepancheg/grpc-rust#62]
Hi @stepancheg

I see that GrpcServer has some public functions (local_addr, is_alive), but users can't use them in the generated server.

I think it is better to export these functions or public the GrpcServer directly for outside usage. E,g in our tests, we want to use "127.0.0.1:0" to avoid duplicated listening port problems if use the fixed port, but we can't know the real listening address if we use "127.0.0.1:0" unless local_addr is exported.

**Comment by stepancheg** [comment]
I made field public for now.
