### ISSUE TITLE
Document how to use grpc-compiler

### ISSUE THREAD

**Issue by vrusinov** [stepancheg/grpc-rust#7]
It is not immediately clear how to compile grpc to rust, docs should be updated. I can see some stuff from `grpc-examples/gen-rs.sh` but it can be documented better.

I may be able to submit pull request once I figure this out (disclaimer: I am noob in Rust).

PS: can this be done via cargo?

**Comment by stepancheg** [comment]
> I may be able to submit pull request once I figure this out

Pull requests, in particular, documentation pull requests are always welcome.

> can this be done via cargo?

Done what? You could install protoc plugin from crates onces it uploaded to crates same way it can be done with [protobuf](https://github.com/stepancheg/rust-protobuf).

**Comment by stepancheg** [comment]
> can this be done via cargo?

Ah, you mean generate rust code right from cargo. It can be done, some people did it, but I don't know details. You can find some details [there](https://github.com/stepancheg/rust-protobuf/issues/57).

**Comment by vrusinov** [comment]
> Ah, you mean generate rust code right from cargo. It can be done, some people did it, but I don't know details. You can find some details there.

Yes, thanks for the pointer. Seems a bit more complicated, so probably not worth the effort describing in readme. Maybe with some more work https://github.com/dwrensha/capnpc-rust it can be feasible.

Anyway, pull request is going your way, and I'm happy to address any comments since my instructions could be too naive.
