### ISSUE TITLE
tags and releases

### ISSUE THREAD

**Issue by cyphar** [stepancheg/grpc-rust#71]
Currently the version of `grpc-rust` in `crates.io` is 4 months out of date. While that's fine, in addition releases are not tagged in this project, which means that it's non-trivial to go back in time and figure out what version of the examples should be used for a particular version of the `grpc` library.

Is it possible for you to tag the commits that correspond to the released code on `creates.io`. Also would you mind cutting a new release?

**Comment by stepancheg** [comment]
Well, it's hard to make tags and version when implementation is not complete.

Anyway, I've just create version and tag 0.1.2.

**Comment by cyphar** [comment]
@stepancheg Of course, my point was that if you choose to publish releases to crates.io it would be very useful to users to also tag the commit that you pushed (so we can read the docs and the code at that snapshot).
