### ISSUE TITLE
Make openssl an optional dependency for real

### ISSUE THREAD

**Issue by matklad** [stepancheg/grpc-rust#72]
Hi! Currently `openssl` dependency is specified as `openssl = { version = "0.8", optional = true }`, but in fact it is **not** optional, because `httpbis` is not optional, and it depends on `native-tls` :)

**Comment by matklad** [comment]
Hm, and maybe everything works as intended? native-tls depends on openssl only on linux.

Feel free to close then!

**Comment by matklad** [comment]
Ah, just found https://github.com/sfackler/rust-native-tls/issues/33, sorry for the noise!

**Comment by stepancheg** [comment]
Actually, it is just a piece of garbage from using old implementation of tls. Fixed now. Thanks!
