### ISSUE TITLE
Could not find `bytesx` in `httpbis`.

### ISSUE THREAD

**Issue by thedodd** [stepancheg/grpc-rust#79]
```
$ cargo build
   Compiling grpc v0.1.7
error[E0432]: unresolved import `httpbis::bytesx::bytes_extend_with`
  --> /Users/adodd/.cargo/registry/src/github.com-1ecc6299db9ec823/grpc-0.1.7/src/grpc_http_to_response.rs:16:5
   |
16 | use httpbis::bytesx::bytes_extend_with;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `bytesx` in `httpbis`

error: aborting due to previous error

error: Could not compile `grpc`.

To learn more, run the command again with --verbose.
```

Looks like some very recent changes to httpbis may have caused this. Can't seem to figure out how to get Cargo to use an older version of the dep.

**Comment by stepancheg** [comment]
My bad. I've just uploaded grpc v0.1.8 which should compile against latest httpbis.

I don't know how to override dependency version.

**Comment by thedodd** [comment]
+1 thanks, boss. Looks like this is a way to override a dep: http://doc.crates.io/specifying-dependencies.html#overriding-dependencies
Haven't actually tested it out yet though.
