### ISSUE TITLE
Crates.io depends on wrong httpbis

### ISSUE THREAD

**Issue by bspeice** [stepancheg/grpc-rust#87]
Currently, grpc v0.1.11 depends on httpbis v0.2.0, which isn't compiling currently (due to error: `pub(restricted)` syntax is experimental (see issue #32409)).

While I see you marked in the Cargo.toml it wants 0.3.1, [crates.io](https://crates.io/crates/grpc) claims a dependency on ^0.2.

**Comment by bspeice** [comment]
As an update: If you use grpc from Git instead, the dependency works correctly, but the same issue is there. I think the actual solution is that a beta (currently 0.19.0) compiler is required, which would be helpful to note in the setup instructions.

**Comment by stepancheg** [comment]
`pub(restricted)` is [stable in rust 1.18](https://github.com/rust-lang/rust/blob/master/RELEASES.md), and latest stable is 1.18.

**Comment by stepancheg** [comment]
Here is the [proof that httpbis works in stable](https://travis-ci.org/stepancheg/rust-http2/jobs/248602287).

**Comment by bspeice** [comment]
No kidding, looks like I was on a different compiler than I thought I was. My apologies.
I would still contend that I'm installing httpbis 0.2.0, where the Cargo.toml specifies 0.3.1.

**Comment by stepancheg** [comment]
Could you please explain again what is the issue?

I've just tried to compile dummy project with `Cargo.toml`:

```
[package]
name = "xxxx"
version = "0.1.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]

[dependencies]
grpc = "0.1.11"
```

It compiles fine.

**Comment by bspeice** [comment]
Me not thoroughly checking the released vs. master Cargo.toml. I thought it should have been building against 0.3.1, but I was mistaken. My apologies. All good!

**Comment by stepancheg** [comment]
No problem. If you have any more questions, please don't hesistate to ask!
