### ISSUE TITLE
Support UNIX domain sockets

### ISSUE THREAD

**Issue by netvl** [stepancheg/grpc-rust#91]
Is it possible to support UNIX domain sockets as a transport for gRPC? For example, grpc-go [supports](https://github.com/grpc/grpc-go/issues/73) them, while grpc-java uses Netty which [can be configured](https://github.com/grpc/grpc-java/issues/1539) to support UNIX sockets.

**Comment by bblancha** [comment]
It looks like Stepan is away for some time. 

It seems that supporting unix domain sockets should be possible. It will take some changes in rust-http2. I am working on that, but am new to Rust so it may take some time. I will update here If I can get it figured out.

**Comment by stepancheg** [comment]
I'm sorry, I've just changed an employer and very busy.

Yes, I think UDS would be a good addition. I doubt I will have time in foreseeable future to do it myself, but it someone wishes to implement it, I could help/explain/review.

**Comment by bblancha** [comment]
Here's the first pass of enabling UDS in rust-http2:
https://github.com/stepancheg/rust-http2/pull/15

I'll work on at adapting grpc-rust to those changes in the next few days.

**Comment by bblancha** [comment]
Once the rust-http2 change is in place, I'll open a PR in this repository using the following branch:
https://github.com/bblancha/grpc-rust/tree/unix_socket

**Comment by stepancheg** [comment]
Published 0.6.0

Thank you!
